### ISSUE TITLE
Cannot connect to Mac listener from other machines

### ISSUE THREAD

**Issue by greyshirtguy** [JeffreyDavidsz/VICREO-Listener#1]
As per doco: https://docs.python.org/2/howto/sockets.html

Which says...
A couple things to notice: we used socket.gethostname() so that the socket would be visible to the outside world. If we had used s.bind(('localhost', 80)) or s.bind(('127.0.0.1', 80)) we would still have a “server” socket, but one that was only visible within the same machine. s.bind(('', 80)) specifies that the socket is reachable by any address the machine happens to have.

Suggest to change line 61
server_address = ('localhost', 10001)
server_address = (socket.gethostname(), 10001)

**Comment by JeffreyDavidsz** [comment]
Thank you for pointing that out! socket.gethostname() would get me in trouble as you try to connect to for a name. I've changed the code in a new release

**Comment by greyshirtguy** [comment]
Ah there you go, binding to 127.0.0.1 only allows local connections, binding to the hostname (IP) only allows remote connections...and binding to '' allows both!!! (I've learned something today!)
