### ISSUE TITLE
Possible to send keycode instead of the characters

### ISSUE THREAD

**Issue by theColourSpace** [JeffreyDavidsz/VICREO-Listener#10]
Is it possible to enable the ability to send a keycode instead of a character, for activating shortcuts that are triggered by the numpad but not the number itself, for example.

Thanks.

**Comment by JeffreyDavidsz** [comment]
At this moment not, focus for now is to make a better osx version

**Comment by theColourSpace** [comment]
Understood, if others run into this, I found using autohotkey and open file allowed a work around.

**Comment by JeffreyDavidsz** [comment]
Ok so I've created a little better OSX version. Let's see how we can implement this

**Comment by JeffreyDavidsz** [comment]
How would you like to use this?

**Comment by greyshirtguy** [comment]
Pull request 18 might address this in some use cases

**Comment by JeffreyDavidsz** [comment]
Send process to OSX is using keycode with applescript. For windows there is no solution yet. If I can find the time I'll write a new library.
