### ISSUE TITLE
Support for more keys

### ISSUE THREAD

**Issue by Wiethoofd** [JeffreyDavidsz/VICREO-Listener#11]
There are a lot of keys already supported, but the pynput lib supports [a lot more](https://pynput.readthedocs.io/en/latest/keyboard.html#pynput.keyboard.Key)

I would like to see support for `ScrollLock` and `Pause` as well as being able to differentiate between the _left_ or _right_ `Ctrl`, `Shift` & `Alt` (and `cmd`) when sending commands.

Possibly supporting more function keys, which aren't available as physical keys on a regular keyboard (F11-F20), but can still be mapped within software, or are on custom keyboards/ones with programmable layers.

Also some documentation and/or support for the numpad (and their numlock disabled counter parts) would be appreciated (without having to resort to keycodes #10)

**Comment by greyshirtguy** [comment]
Pull request 18 might help with this - for some cases...(MacOS only)

**Comment by JeffreyDavidsz** [comment]
Closing this one as the pynput lib is no longer used

**Comment by Wiethoofd** [comment]
The issue/request is still valid, even with the pynput library not being used anymore.

Adding the F13-F20 keys would still be nice to have, to allow for usage outside of regular available keys, for instance Companion + OBS. Same for the Scroll Lock, Right Ctrl & AltGr, the Win key and the various non-numeric numpad ones.
