### ISSUE TITLE
Opening a file

### ISSUE THREAD

**Issue by scaryxpuppy** [JeffreyDavidsz/VICREO-Listener#12]
When trying to OPEN A FILE directly from companion, it doesn't seem to work ... for example, a file on my desktop is : 

/Users/pmavmacbookpro/Desktop/invoice-2545.pdf

But this doesn't seem to open ???

Any ideas

**Comment by JeffreyDavidsz** [comment]
I thought it worked before, I've changed the way it works and uploaded a new release.

**Comment by scaryxpuppy** [comment]
That's great - hopefully a useful addition ! Thanks. P
