### ISSUE TITLE
Spacebar

### ISSUE THREAD

**Issue by charliticus** [JeffreyDavidsz/VICREO-Listener#13]
Using Companion 2.0.0
Latest version of Listener
The idea is to initiate the press of the spacebar using a Stream Deck. That function appears to add a space as a text entry and not necessarily registering a spacebar press. The software I'm attempting to trigger is Kinesys Vector. Pressing the spacebar affects the program. As it works now, this isn't doing anything but adding a space in a text field. Pressing the spacebar on the machine works properly, it's just the keyboard emulation part doesn't seem to work.

**Comment by greyshirtguy** [comment]
Pull request #18 may help with this in some cases (MacOS only)

**Comment by charliticus** [comment]
This was PC to PC.

**Comment by JeffreyDavidsz** [comment]
You can try the new version? It's a pre-release and runs on a different platform (nodejs)

**Comment by JeffreyDavidsz** [comment]
Just tested this with qlab (which is on OSX), space will register a spacebar not text. But feel free to test in windows. Closing this for now. If the problem still exist on the newer version, let me know in a new issue please
