### ISSUE TITLE
How to add to companion

### ISSUE THREAD

**Issue by kd8ssq** [JeffreyDavidsz/VICREO-Listener#14]
I cannot figure out how to add the vicreo module to companion.  I don’t find that module when I search for it in the list in companion.  I’m running Companion 1.3.0

**Comment by JeffreyDavidsz** [comment]
Unfortunately that's build later. try to download from builds.bitfocus.io to use the listener. look for a folder branche. and use a 1.4 version. This should be the new stable soon

**Comment by kd8ssq** [comment]
Got it.  Thanks!
