### ISSUE TITLE
Linux release

### ISSUE THREAD

**Issue by dewiweb** [JeffreyDavidsz/VICREO-Listener#15]
Hello,
Do you think possible to release for linux architecture?

**Comment by boscacci** [comment]
I have a request to make the <SKE> functionality work on Linux, specifically Centos, for DaVinci Resolve power users. I will try my hand but can't promise anything, really not sure how Quartz, objc, psutil work or even how operating systems work

**Comment by boscacci** [comment]
Struggling to understand how to build this app with [pyinstaller](https://pyinstaller.readthedocs.io/en/stable/when-things-go-wrong.html), am poring over the pyinstaller docs...if I grok this I will try to write repo-specific build instructions into my fork here

**Comment by JeffreyDavidsz** [comment]
Hi Guys, currrently I've made a nodejs version of the app, but it needs testing and building. Hopefully it will come soon. @boscacci you can run the pyinstaller script of without

**Comment by JeffreyDavidsz** [comment]
`pyinstaller VICREO_Listener_OSX.spec`

**Comment by boscacci** [comment]
> `pyinstaller VICREO_Listener_OSX.spec`

Just had to change paths in `VICREO_Listener_OSX.spec` in order to get this to work. Thanks!

**Comment by JeffreyDavidsz** [comment]
Great

**Comment by JeffreyDavidsz** [comment]
@dewiweb there is a armv7l version build on a raspberry now. I've run it on my PI and tested it quickly. So do I need to build for x86_32/64 also?

**Comment by dewiweb** [comment]
@JeffreyDavidsz , Yes we run it on Ubuntu 18.04 64bits so it could be interesting to have a release for

**Comment by JeffreyDavidsz** [comment]
I've created an automatic builder on travis for amd processors. It's not tested by me yet, but feel free to try and let me know! Search for it in the 2.0.7 release (in the naming you'll find 2.0.8)
