### ISSUE TITLE
UDP

### ISSUE THREAD

**Issue by Flummip** [JeffreyDavidsz/VICREO-Listener#19]
Hello, 

Could you make it possible that vicreo could receive udp signal?

Best regards Tobias

**Comment by JeffreyDavidsz** [comment]
Hi Tobias, sorry for the delay. First thought was, no problem. But I want to keep the program as simple as possible as its a tool running in the background. What kind of software/hardware are you using to connect? I could write a custom version or you can do yourself (sourcecode is open).

**Comment by JeffreyDavidsz** [comment]
Closing this as no reaction has come
