### ISSUE TITLE
Close program in Windows

### ISSUE THREAD

**Issue by JeffreyDavidsz** [JeffreyDavidsz/VICREO-Listener#2]
Closing the systray actually leaves the rest of the program running.

**Comment by greyshirtguy** [comment]
I'm not Python expert - just a black-belt in Google-Fu.
https://stackoverflow.com/questions/16734534/close-listening-socket-in-python-thread
https://stackoverflow.com/questions/19790570/using-a-global-variable-with-a-thread

The following works in my quick testing....

#systray functions
def on_quit_callback(systray):
	print('shutdown program from menu')
	global _LOOP #flag to Python that _LOOP is the global variable (not a new local variable in this callback function
	_LOOP = False
	socket.socket(socket.AF_INET, socket.SOCK_STREAM).connect( ('localhost', 10001)) # jump out of the socket wait state (Socket block execution, while waiting for a new connection)
	sock.close()

**Comment by JeffreyDavidsz** [comment]
@greyshirtguy I've started with python a few weeks ago :-) I really appreciate your feedback. Following your code from the stackoverflow site, works. It closes down the program correctly. Thanks!
