### ISSUE TITLE
[question] process for MacOS OSwide Mute & Unmute

### ISSUE THREAD

**Issue by TreborKutscher** [JeffreyDavidsz/VICREO-Listener#20]
Hello Jeffrey,
Iam searching for the right process to apply the mute & unmute command for MacOS on the System level.
One day i was chellenged by dorian meind to get him the first frame of each Clip in PlaybackProPlus so he can see and start it in the presentationswitcher.
I tried the mute command on Powerpoint, while a combination for launching the presentation even if powerpoint is in background works.
I considering it is not right process.

And You may considering make the MacOS Mute; Unmute, VolUP, VolDown available as an Preset in Companion

Best Regards Trebor Kutscher

**Comment by JeffreyDavidsz** [comment]
Hi Trebor, my problem is I hardly use OSX. But its a good suggestion!

**Comment by JeffreyDavidsz** [comment]
Hi Trebor, do you have the applescript for volume?

**Comment by TreborKutscher** [comment]
Hello Jeffrey,

 

Yes i can give it to you.

 

For Mute:         set volume "0" 

For Unmute:     set volume "100"

 

 

But originally Sebastian "Milse" Mill gave it to me.

 

It is really simple. If i complie them it works great. Only distributing on other Machines is a bit nasty because of the security nag.

 

Greetings Paul

 
 

Gesendet: Freitag, 12. Juni 2020 um 06:51 Uhr
Von: "Jeffrey Davidsz" <notifications@github.com>
An: "JeffreyDavidsz/VICREO-Listener" <VICREO-Listener@noreply.github.com>
Cc: "Trebor Kutscher" <palabs@web.de>, "Author" <author@noreply.github.com>
Betreff: Re: [JeffreyDavidsz/VICREO-Listener] [question] process for MacOS OSwide Mute & Unmute (#20)


 

Hi Trebor, do you have the applescript for volume?

**Comment by JeffreyDavidsz** [comment]
Yeah that's a workaround. Unmuting this way will set the volume to 100% and not the previous state. I found the solution and just tested it on OSX. Will be in the 2.0.5 release.
