### ISSUE TITLE
V2.0.1 on Mac  not running commands, error occurred in the main process

### ISSUE THREAD

**Issue by Tw0bit** [JeffreyDavidsz/VICREO-Listener#27]
V2.0.1 is running now on OSx (10.15.5) however when sending commands from Companion nothing happens.

Seems the service is working (as it connects when open on the provided port). When accessing via webpage (localhost:10001) the following error occurs -
<img width="829" alt="Screen Shot 2020-06-11 at 6 05 44 pm" src="https://user-images.githubusercontent.com/2338536/84361104-8048dd80-ac0e-11ea-8340-45b25872df34.png">

is there a log/debug at all? V2.0.0 while it didnt load - it had a top menu
<img width="448" alt="Screen Shot 2020-06-11 at 6 14 39 pm" src="https://user-images.githubusercontent.com/2338536/84361785-82f80280-ac0f-11ea-88cb-e3388cab312d.png">

V2.0.1 however does not change the top bar and shows only the previous app menu
<img width="416" alt="Screen Shot 2020-06-11 at 6 14 53 pm" src="https://user-images.githubusercontent.com/2338536/84361811-93a87880-ac0f-11ea-856a-391f19e11f54.png">

**Comment by Tw0bit** [comment]
Tried the 2.0.1 build on windows. Accessing the url/port in a browser brings up the same error.

When sending a command via companion it throws an error
![Annotation 2020-06-11 182133](https://user-images.githubusercontent.com/2338536/84362504-aec7b800-ac10-11ea-8a80-c9efc19b3888.jpg)

**Comment by JeffreyDavidsz** [comment]
You cannot access the program via browser.

**Comment by JeffreyDavidsz** [comment]
Wait a few days, so I can properly test the osx version

**Comment by Tw0bit** [comment]
No trouble at all.

V2.0.1 > On windows when companion sends a command a JS error appears (see previous comment). On mac when companion sends a command nothing happens.

**Comment by JeffreyDavidsz** [comment]
@Tw0bit you are using an older version of companion, which is fine but in the support for the older version I made an typo. fixed that. In the new release it will work. Meanwhile try alt/tab as combination to see if it work for you (windows)

**Comment by Tw0bit** [comment]
I am running a recent build of v2.0.0 of companion 
![F5436F15-E197-4B7B-A272-945D36085530](https://user-images.githubusercontent.com/2338536/84443445-f71fbe00-ac82-11ea-9d21-45d667339e87.jpeg)

**Comment by JeffreyDavidsz** [comment]
Yes in later builds I've included the option to choose a port number and to choose between Python build and Nodejs build (which I'm going to rename I guess). If you use older versions of Companion (yes that's also 2.0) the protocol is for the Python build. Of course many people will still use that. So I've build support for that. The command/windows and escape key options gave an error or did nothing (in the newer version the library uses a different option for that), that has been fixed. Some small tweaking/enhancement to do, but the app should work as expected now. Can you try 2.0.2?

**Comment by Tw0bit** [comment]
I have just updated Vicreo 2.0.2 and Companion Beta 2.0.0-29d8d90-2402 on Windows and seems to work well. I will update with Mac shortly.

**Comment by JeffreyDavidsz** [comment]
New release 2.0.3 available
