### ISSUE TITLE
Can't use <KCOMBO>cmd<AND>single-key

### ISSUE THREAD

**Issue by greyshirtguy** [JeffreyDavidsz/VICREO-Listener#3]
Cannot use <KCOMBO>cmd<AND>single-key
eg <KCOMBO>cmd<1> returns 'wrong key'

This is because #find second block of code tries to match the second string to one of the modifer arrays - else it returns 'err'
Line 100:
command2 = modifier.get(command2.lower(), 'err')

Perhaps changing to something like this (allows KCOMBO with modifier key AND single keys and also protects against clients that append \r\n or \n to sent commands)
					#find second
					command2 = tcpString[tcpString.index('<AND>')+5:]
					if len(command2)>1:
						command2 = command2.lower().rstrip() # Strip trailing whitespace (including any \r\n that may have been sent)
						command2 = modifier.get(command2, command2[0]) #Find matching modifier or treat as single key

Also suggest update the doco to point out first string in KCOMBO must be a modifier, while the second can be either a modifier or single-key

**Comment by JeffreyDavidsz** [comment]
It's build to except a single key or a modifier. when you send anything over a single key it will search for a modifier, when none is found in the dictionary it returns an error. this way spaces and other stuff returns errors. I did apply the remove string now on the second command, for if someone evidently did press space.
please check if you send `<KCOMBO>cmd<AND>1` and not `<KCOMBO>cmd<AND><1>`
