### ISSUE TITLE
Companion -2.0.0-ab759d3-2405 has no vicreo-hotkey module

### ISSUE THREAD

**Issue by Tw0bit** [JeffreyDavidsz/VICREO-Listener#31]
Sorry, not sure where this bug request should go. Just updated companion and in companion-2.0.0-ab759d3-2405 (windows) there is no module for vicreo: 15. 18:44:55 instance(vicreo-hotkey): Configured instance vicreo-hotkey could not be loaded, unknown module

**Comment by Tw0bit** [comment]
It was there in companion-2.0.0-859914b-2404 (windows)

**Comment by JeffreyDavidsz** [comment]
Mmmm GitHub push error, I'll trigger a new build 2406. Will be there in a few minutes
