### ISSUE TITLE
vicreolistener page up & page down doesn't work

### ISSUE THREAD

**Issue by hellebaard666** [JeffreyDavidsz/VICREO-Listener#32]
vicreolistener page up & page down doesn't work in companion /streamdeck
other special keys like space bar or Function buttons, arrows work fine...

only page up and page down doesnt work.
Thx 4 help

**Comment by JeffreyDavidsz** [comment]
Fixed in 2.0.6 (building now)

**Comment by hellebaard666** [comment]
Great! Thank you very much!
