### ISSUE TITLE
V2 not working on Mojave

### ISSUE THREAD

**Issue by caleymw** [JeffreyDavidsz/VICREO-Listener#36]
I tried V2.0.7 on OSX Mojave in conjunction with Companion. Pushing buttons in Companion I could see the correct results in the log in Vicreo Listener, but Listener didn't seem to be pressing any keys in my programs. I tried on two Macbook Pros both using Mojave with the same results. Downgraded through the V2 versions with the same results. Downgraded to V1.40 and it works! In V1.40 I received a prompt to allow access at System Prefs->Security And Privacy->Privacy->Accessibility which I did not receive in V2 versions. Happily using V1.40 so thanks!

**Comment by JeffreyDavidsz** [comment]
Could you send me the log of the 2.0.7 please (so the commands the program received)? I assume you are using companion 1.4? Some backwards compatible issues I think

**Comment by caleymw** [comment]
Thanks for the quick response!! Here's an example log from 2.0.7. This
works fine in Vicreo 1.40 but I get no action from Vicreo v2. Companion is
V1.4.0. Again, I think Companion is talking to Vicreo without any trouble
but Vicreo isn't controlling the OS properly.

13:41:31 <KCOMBO>cmd<AND>1
13:41:30 <SPK>right
13:41:29 <SPK>left

**Comment by JeffreyDavidsz** [comment]
Looks like the build wasn't updated and an older version stayed there. I replaced it with version 2.0.8. Which has some small changes in logging. You'll find it under the 2.0.7 release as I want to test the 2.0.8 on windows first

**Comment by caleymw** [comment]
2.0.8 now prompts for system control and works as expected. Thanks!!

**Comment by JeffreyDavidsz** [comment]
Cool I think you are the first to use it, have fun with it!
