### ISSUE TITLE
Subsequent connections not processed until previous connections are closed

### ISSUE THREAD

**Issue by greyshirtguy** [JeffreyDavidsz/VICREO-Listener#4]
With MacOS listener: You can connect from as many clients as you like - it will accept connection.
But only the first one will process and reply to commands - until it closes and processing quickly proceeds with next connection (including anything that was sent, but not processed).
Perhaps consider limiting to one connection - maybe reply back saying - "I'm busy talking to client_address"
(Unless you want to setup a threaded server to concurrently handle multiple connections!!!!)

**Comment by JeffreyDavidsz** [comment]
The idea is to support multiple connections from different machines, revert to 1 connection only for now
