### ISSUE TITLE
Cannot open file, syntax error

### ISSUE THREAD

**Issue by acidfrost** [JeffreyDavidsz/VICREO-Listener#44]
Hi,

I'm using Companion 2.0beta and Vicreo 2.0.9 and I cannot open a file.
I keep getting the error: "please change to new syntax"

I've tried entering the follow file paths: C:\photo.png, C:/photo.png, "C:\photo.png" and "C:/photo.png".
They all give me this error. There are no instructions anywhere that gives an example of the path, except a sentence that says to use blackslash in Companion.

Thank you

**Comment by JeffreyDavidsz** [comment]
In the instance settings of Companion / VICREO select version > 2.0.5 (which is what you have I assume)

**Comment by acidfrost** [comment]
I updated companion. I was on an older version of the Beta. I see the official release is now out and it works.
Thanks!
