### ISSUE TITLE
Numpad Return key

### ISSUE THREAD

**Issue by MisplacedDragon** [JeffreyDavidsz/VICREO-Listener#46]
Looking for the possibility of having the Numpad Return key added, specifically for use in Companion. I have a piece of software that doesn't have a way to remap keys, and apparently it's specifically looking for the numpad Return key, rather than the Enter key.

If there's a way to emulate already, that'd be fine too!

**Comment by JeffreyDavidsz** [comment]
There is a keypad enter which you can use on OSX, doest that help?

**Comment by JeffreyDavidsz** [comment]
The problem is that the keycode is in both ways 13

**Comment by JeffreyDavidsz** [comment]
close due no reply
