### ISSUE TITLE
OBS 26 doesn't receive single keys or three key combinations anymore

### ISSUE THREAD

**Issue by DachsbauTV** [JeffreyDavidsz/VICREO-Listener#53]
As the title says, ever since updating to OBS 26 my shortcuts (through companion and Vicreo) wouldn't work anymore.

OBS still receives the keys via a regular keyboard.

I've tried three keys, single hot key and key press.
None has made it to OBS.

Until this Vicreo Listener has worked like a charm and I really appreciate the amazing work you did here.

**Comment by JeffreyDavidsz** [comment]
I've heard this before. To be clear the only update you did was updating OSB right? I might look into that

**Comment by DachsbauTV** [comment]
Correct. OBS from 25 to 26 and Vicreo is on 2.1.0. but was already on that with OBS 25

**Comment by DachsbauTV** [comment]
fyi I've changed the physical connection of the streamdeck and the companion app to a second PC on the same network and now it's working again.
Absolutely no idea why.

**Comment by DachsbauTV** [comment]
ok another find: it's still not solved, it does only work when the vicreo listener is on top and in focus

**Comment by JeffreyDavidsz** [comment]
This is a security issue not mainly related to OBS, I'll close this
