### ISSUE TITLE
I don't understand how, and where, to put "key press, space bar" ???

### ISSUE THREAD

**Issue by franklyray** [JeffreyDavidsz/VICREO-Listener#54]
I have Vicreo Listner on Computer 2. Computer 1 has a Stream Deck and ATEM Mini Pro attached. I am running Companion. Everything is on same Ethernet. 

I am not a programmer so I appreciate your help Jeff. 

![Vicreo confusion 10 21 20](https://user-images.githubusercontent.com/4950599/96807668-2985b880-13e5-11eb-96f6-a2707e581a64.jpg)

**Comment by JeffreyDavidsz** [comment]
Type space or spacebar (I forget) or use the special key action, I believe it's there also

**Comment by franklyray** [comment]
Thanks. That worked. I have a better understanding now. BUT, of course.

Has anyone developed a PowerPoint list of commands for the 2nd computer?

**Comment by franklyray** [comment]
I found the PowerPoint shortcuts here: https://www.howtogeek.com/362142/all-the-best-microsoft-powerpoint-keyboard-shortcuts/

**Comment by JeffreyDavidsz** [comment]
Don't really understand your question, but you can drag and drop presets from companion on a button. There are presets for windows powerpoint

**Comment by franklyray** [comment]
I'm getting very comfortable with it. Donation to follow this week.

**Comment by JeffreyDavidsz** [comment]
Nice!
