### ISSUE TITLE
Vicreo not pressing keys [ SOLVED]

### ISSUE THREAD

**Issue by renemistergiant** [JeffreyDavidsz/VICREO-Listener#56]
[SOLVED] Set hotkey version in companion to: Hotkey version > 2.0.5

I have Streamdeck + Companion + Vircreo running on a windows machine perfectly.

I just installed the same on a second windows machine, Vicreo is getting the commands from Companion.
And you see them coming in the log, but then nothing happens. 
I tried versions 2.0.8, 2.0.9 and 2.1.0.

Tried running in admin mode and in windows 8 compatibility mode. 

The log just shows:
12:56:51 received: <KPRESS>m
12:48:22 received: <KCOMBO>ctrl<AND>c

-------------------------------------------------
and then I found the solution: 
Set hotkey version in companion to:
Hotkey version > 2.0.5

Just posting here if someone else has the same problem.

**Comment by JeffreyDavidsz** [comment]
Thanks for updating the post
