### ISSUE TITLE
High CPU usage for vicreo listener

### ISSUE THREAD

**Issue by singletrackrecs** [JeffreyDavidsz/VICREO-Listener#57]
Hi, I'm experiencing constant CPU usage of over 400% by the Vicreo-listener helper process. I'm on Catalina 10.15.7. V2.1.0 of Vicreo listener

Is this a known issue?

Thanks so much

**Comment by JeffreyDavidsz** [comment]
It's not, I need to look into it. Is something connected to it, like companion. Is it constantly?

**Comment by singletrackrecs** [comment]
Hi Jeffrey. Ok no worries, yes companion is connected and the usage is constant. I’m a brand new user just trying out the stream deck for the first time. So using all latest downloads, but a noob on this platform. 

Workaround for the moment is I can use qlab apple scripts for key presses. 

Thanks for the quick reply. 

Chris

**Comment by JeffreyDavidsz** [comment]
Is this still actual? Meanwhile I received 0 reports about this
