### ISSUE TITLE
New Feature: Click/Right Clic

### ISSUE THREAD

**Issue by ROv2** [JeffreyDavidsz/VICREO-Listener#59]
A simulated Mouse Click/ Right Click would be nice. I'm using an old visual-software on an X-serve, that doesn't support hotkeys. For selecting a videofile, you need to double-click on it. It would be nice if that could be remote-controlled.

**Comment by JeffreyDavidsz** [comment]
Currently the robotjs library used in windows is not being updated by the creator. I'm in the process of creating it natively in C++. I'll add the leftlick and rightclick. There's no mouse movement though, is that fine?

**Comment by JeffreyDavidsz** [comment]
Adding to companion and version 3.0.0 of the listener
