### ISSUE TITLE
Change the executable name to a consistent name

### ISSUE THREAD

**Issue by fheinonen** [JeffreyDavidsz/VICREO-Listener#6]
Currently the executable name changes at every new version, unfortunately this makes maintaining shortcuts really hard when updating. Especially on multiple computers. Please change the released executable name to a consistent one, eg. vicreo_listener.exe

**Comment by JeffreyDavidsz** [comment]
Good tip! from now on I'll keep the naming the same e.g. vicreo_listener_windows.exe and vicreo_listener_osx each release
