### ISSUE TITLE
Special / Combination keys not working

### ISSUE THREAD

**Issue by TFolster** [JeffreyDavidsz/VICREO-Listener#61]
Companion 2.1.2
Vicreo 2.1
Windows 10  Home

When using stringmessage message types fine. Using Special character: ENTER does not hit enter, instead types <SPK> ENTER.

Windows key combinations do not work when using Windows (Command) key.

**Comment by JeffreyDavidsz** [comment]
String message does indeed do what it needs to do... use a key press for an [enter].
Windows key have been tested, so what doesn't work?

**Comment by TFolster** [comment]
I found my issue in Companion. There is an option in Companion in the Vicreo instance setup to work with pre 2.0 or post 2.0 Vicreo. I changed it to pre and everything stopped working. When I switched it back to post things began working as expected.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/ghei36>

________________________________
