### ISSUE TITLE
MacOS Big Sur on M1 doesn't send keys

### ISSUE THREAD

**Issue by markshead** [JeffreyDavidsz/VICREO-Listener#62]
Windows is running BitFocus and MacOS Big Sur on an M1 mac is running Vicreo. I want to send a space from windows to macos. Vicreo connects and shows that it is getting the space bar, but it doesn't actually get realized as if someone pushed the space bar on MacOS.

In the log:
received: {"key":"space","type":"press","modifiers":[]}

The same setup worked fine with a non Big Sur non M1 laptop. Is this known to work?

**Comment by JeffreyDavidsz** [comment]
I personally don't have a M1, but I can imagine new security measures. Do other keys work?

**Comment by markshead** [comment]
I haven't been able to find any keys that work. I've tried up and down arrows, page up and page down, and space bar. I'm not seeing any type of error though, but maybe I don't know where to look.

Does it work with Big Sur on Intel processors?

**Comment by JeffreyDavidsz** [comment]
On Mac you need to give permissions, my first guess is that you haven't give them yet? Somewhere near accessibility settings

**Comment by markshead** [comment]
That was it:
System Preferences > Security & Privacy > Privacy > Accessibility
Then allows Vicreo to control the computer. 

Thank you!
