### ISSUE TITLE
Shell Commands on Windows

### ISSUE THREAD

**Issue by epsom3d** [JeffreyDavidsz/VICREO-Listener#63]
Hi,

I'm using Vicreo Listener 2.1.0 on a Windows 10 PC.

I'm communicating with it using another Windows 10 PC running the latest version of Bitfocus Companion as at 16 Jan 2021 (not sure where the version number is) and Stream Deck Version 4.9.2.13193.

I am trying to make a small PC into a media player and want to run the command:

`start wmplayer "c:\users\et\Desktop\Videos\ParkVideo.mp4" /fullscreen`

...in order to run videos full screen after a keypress on the Stream Deck.

However, I am finding that shell commands are not working as I expect.  Here are some examples:

Send Shell Command: `start cmd`

- This works fine and a Command Prompt appears

Open a file:  `c:\users\et\Desktop\Videos\ParkVideo.mp4`
- This works fine and the video starts

Shell Command: `start wmplayer "c:\users\et\Desktop\Videos\ParkVideo.mp4" /fullscreen`
- This doesn't work - nothing happens.

I have also tried putting this into a batch file and running the batch file as a shall command.  It works when I click the batch file but not when I try to run it via the button press on Stream Deck.

Am I formatting my shell commands incorrectly?

**Comment by JeffreyDavidsz** [comment]
Try to escape the " by using \"

**Comment by epsom3d** [comment]
I'm sorry but I don't understand what you mean.  Could you humour me and explain what you mean when you say 

> Try to escape the " by using ".

My apologies - I'm not a developer.

**Comment by JeffreyDavidsz** [comment]
Thats me typing on the phone should by \\"

**Comment by epsom3d** [comment]
Ah, I think I see what you're saying.  I was wondering about the quotation marks - let me see if I can make it work...

**Comment by epsom3d** [comment]
After trying a lot of different things I have finally found the answer!!!!!!!!

Here is a working example:

`start wmplayer \"c:/users/et/Desktop/Videos/ParkVideo.mp4\" /fullscreen`

What I discovered is that you have escape the quote marks as you suggested but also you have to convert the Windows backslashes to forward-facing ones.

This is fantastic.  I can now make a small PC into a remotely-controllable media player!
