### ISSUE TITLE
Question - Start minimized?

### ISSUE THREAD

**Issue by kd8ssq** [JeffreyDavidsz/VICREO-Listener#64]
Running version 2.0.9.  

Is there a way to start the program already minimized?

**Comment by andreassorby** [comment]
Yes! - on windows 10. The windows internal "start minimized" setting in the shortcut links does not work on Vicreo. I would love this to start in the tray only.

**Comment by MCE2021-ui** [comment]
That functionality would be great! :-)

**Comment by JeffreyDavidsz** [comment]
I've added this to 3.0.0. You can choose in the menu, then it will be remembered on the computer. I'll push to github soon
