### ISSUE TITLE
Running in AWS?

### ISSUE THREAD

**Issue by abruptriver** [JeffreyDavidsz/VICREO-Listener#66]
I'm trying to run VICREO-Listener headless on an AWS instance.  Windows server is set to autolog in on boot which I can confirm and the application loads but only seems to work when I remote desktop into the machine in question.  Is it possible to get this to work in this manner?

**Comment by JeffreyDavidsz** [comment]
That would need some testing I guess. The listener simulates keystrokes on Windows on top. But what if no "monitor" is active? Did you try to run a shell script or open a file. If that works then the issue would be with nothing being active. Maybe you could share your use case?

**Comment by abruptriver** [comment]
That makes sense.  I'm trying to send shortcuts to the zoom client in order to Mute/unMute a microphone, etc.  I have the zoom client also auto starting and it is definitely opening because other machines are able to invite the zoom client into a meeting which it then joins.  The keystroke commands coming from companion are not working but as soon as I connect via remote (I'm using teradici) the commands get received without any other changes.

**Comment by JeffreyDavidsz** [comment]
Did you install special GFX drivers? I did some vMix configs on AWS. Might be able to test it against that

**Comment by abruptriver** [comment]
I didn't install anything other drivers than what was included in the teradici marketplace instance.  I believe it already has the latest Nvidia drivers installed for the g4dn.xlarge instance.  However, I think there may be a bigger issue at play.  I did some more testing today and tried running some batch files as you suggested.  I can confirm that the batch files do run while the machine is headless.  I had it open an app via batch file then when I connect to the desktop the app is open.  I was also able to create a batch file that sends key strokes directly to a specific app.  Suspiciously, this also worked perfectly as long as the remote desktop was connected.  Once the machine was headless, this no longer worked.  So I'm guessing this may be a bigger limitation that I'm running into.

**Comment by JeffreyDavidsz** [comment]
Yes this is a windows thing. The listener needs to know where to send the commands and in your case there isnt a destination.
Closing this issue as it's not really a listener issue
