### ISSUE TITLE
Ubuntu shift+printscreen

### ISSUE THREAD

**Issue by alex-p75** [JeffreyDavidsz/VICREO-Listener#67]
Hi,
I use often the shortcut shift + printscreen for taking a screenshot of a selected area, but i cannot set that shortcut in my bitfocus companion.

There is a way?

Thank you

Alessandro

**Comment by JeffreyDavidsz** [comment]
Currently the robotjs library used in windows is not being updated by the creator. I'm in the process of creating it natively in C++. I'll add the key

**Comment by alex-p75** [comment]
Great!

Thank you

**Comment by JeffreyDavidsz** [comment]
Finally time to create new libraries. shift and printscreen are supported. When using companion use combination
