### ISSUE TITLE
How do I get keypresses out of Vicreo?

### ISSUE THREAD

**Issue by BearCubStar** [JeffreyDavidsz/VICREO-Listener#68]
On a Mac, (Catalina 10.15.7)
Companion 2.2.0
Vicreo 2.1.0

No trouble getting keypresses from Companion to Vicreo, they all show up in the log. But how do I make them actually do anything?

Permissions granted: Accessibility - allow to control computer, Input Monitoring - monitor input from keyboard, Automation - System Events.app
Companion Instance set to localhost 10001, Version > 2.0.5
Vicreo set to port 10001

I've tried a bunch of things, from the shortcuts I want to use to single keypresses supposed to interact with the Companion emulator, to the shell command. Shell command doesn't show up at all, nor does stringmessage, Open a file.

Some examples in the log:

0:14:01 received: {"key":"3","type":"press","modifiers":["command","shift"]}
23:57:49 received: {"key":"4","type":"press","modifiers":[]}

**Comment by JeffreyDavidsz** [comment]
Still sound like permissions on Mac, might want to reboot (normally not needed) or missed a permission.

**Comment by BearCubStar** [comment]
Rebooted several times, what other permission should I be seeing?
No option in Location Services, Contacts, Calendars, Reminders, Photos, Camera, Microphone, Speech Recognition, Full Disk Access, Files and Folders or Screen Recording.
Accessibility is on, Input Monitoring is on, and in Automation System Events.app is ticked.

**Comment by BearCubStar** [comment]
Having changed the shortcut to F12, it works, as do a number of other single key presses, but I have not managed to make any combination or three key combinations work.
