### ISSUE TITLE
HOW TO send an object to the listener?

### ISSUE THREAD

**Issue by dimaslusiano** [JeffreyDavidsz/VICREO-Listener#69]
Hello, i like your product a lot because its working with OBS Studio.
Bitfocus companion is kinda heavy for my old computer, so i want to use just VICREO Listener only
(for controlling OBS)
HOW TO send an object to the listener?
I dont know anything about programming, after googling, i try using curl to send object
curl -d '{"key":"F24","type":"press"}' localhost:10001
but not working (Received HTTP/0.9 when not allowed)

how to use command line to send object to listener ?
what program to use? and how? 
Right now I'm using VICREO with AHK and OBS Studio

im sorry but i really dont know

**Comment by dimaslusiano** [comment]
yes! now i know how to do it !
thank you for your amazing program

**Comment by JeffreyDavidsz** [comment]
Your welcome ;-)
