### ISSUE TITLE
F12 - F24

### ISSUE THREAD

**Issue by Yerox-dev** [JeffreyDavidsz/VICREO-Listener#71]
I'm using F12 - F24 for shortcuts, but its not supportet by Vicreo, please fix this

**Comment by fgolman** [comment]
+1 for this as it's a great way to avoid conflict with other F keys (since not a lot of apps use them).

**Comment by JeffreyDavidsz** [comment]
Currently the robotjs library used in windows is not being updated by the creator. I'm in the process of creating it natively in C++. I'll add these keys

**Comment by dimaslusiano** [comment]
yes, vicreo support the, i use all the f1 to f24
im using companion, export to file, edit it using text editor and import it
example
"options":{"specialKey":"F24"}}
or just send object 
{ "key":"F24", "type":"press", "modifiers":[""] }
using packet sender

**Comment by JeffreyDavidsz** [comment]
I've added the extra F-keys to companion also
