### ISSUE TITLE
Feature Request: Focus Window/application

### ISSUE THREAD

**Issue by DachsbauTV** [JeffreyDavidsz/VICREO-Listener#72]
Hey Jeffrey,

I was wondering if it would be possible to add a new functionality to the Vicreo-Listener, which would let the user choose which window is in focus before the keys are send or even send the key combination straight to one application only?

The reason why I came across this idea was because a key combination I was using to control OBS accidentally ended up on my audio mixer and almost blew our soundsystem :D

**Comment by jimyehoo** [comment]
2nd this, need to target app and then gives command is very important than just give commands since any app can pick that up and create chaos

**Comment by JeffreyDavidsz** [comment]
The VICREO Listener is build as a keyboard simulator. That being said I see no way of pointing this in windows. For OSX is a function called processOSX, which will do that. If you know a way to do this on windows, let me know
