### ISSUE TITLE
Issue with ScreenCapturing in Mac

### ISSUE THREAD

**Issue by DavidTNguyen** [JeffreyDavidsz/VICREO-Listener#75]
I am trying to setup a button to perform screen capture on a Mac. Normally, I use Command+Shift+4 for this task. But the Companion button doesn't seem to respond as expected. The cursor should have switched to a crosshair ready for screen capture upon button pressed, but nothing happened. 
1/ Am I configuring it correctly?  
2/ How do I grant Screen Recording permission to Vicreo because it's not listed as one of apps granted with this access?

![2021-04-23 14 57 32](https://user-images.githubusercontent.com/11265859/115943492-debd2a00-a475-11eb-87d7-8dc6b9869de6.gif)

![Screen Shot 2021-04-23 at 8 54 29 PM](https://user-images.githubusercontent.com/11265859/115943579-52f7cd80-a476-11eb-87be-f2fc06955c5e.png)

**Comment by JeffreyDavidsz** [comment]
Took me a while to verify this. Normal function like that seems blocked by the OS. What does work is this: "Send KeyPress To MacOS Process" The process is Finder ANSI_4 Shift Command
