### ISSUE TITLE
Sendstring message is very slow to type out

### ISSUE THREAD

**Issue by KarstenTWolf** [JeffreyDavidsz/VICREO-Listener#79]
When using the Sendstring command from companion it's very slow to type out the message in Windows 10 using VICREO listener V2.1.0.

I believe the issue lies in robot.typestring as outlined here: https://github.com/octalmage/robotjs/issues/530

**Comment by JeffreyDavidsz** [comment]
Thanks for reporting in new release RobotJS will no longer be used
