### ISSUE TITLE
ctrl  From Companion 

### ISSUE THREAD

**Issue by EricKerman** [JeffreyDavidsz/VICREO-Listener#80]
any **ctrl** command from Companion does not trigger an **control** event.  CTRL and V Does nothing.  V works and Shift V works. It is reported in the listener as " 20:17:38 received: <KCOMBO>ctrl<AND>v "but in notepad and other things, it does nothing. Same with any other app that needs Control.

Could it be the difference between CTRL and CONTROL?

**Comment by JeffreyDavidsz** [comment]
When the listener receives ctrlv the command and structure is wrong. Make sure you set the version in Companion and use a combo option to send 2 different keys

**Comment by JeffreyDavidsz** [comment]
closing due no relpy
