### ISSUE TITLE
Wish for adding more "numpad only" keys

### ISSUE THREAD

**Issue by 2mas4556** [JeffreyDavidsz/VICREO-Listener#82]
Would like to have Numpad + / * - and numpadEnter on Windows. Have a graphic program, and some parts of it is based on the numpad, where the numpad+ is preview and the NumpadEnter key is to send it on program, normal Enterkey dont trigger it. And it would be very cool to trigger it all from Vicreo and Companion.

**Comment by JeffreyDavidsz** [comment]
I've added this. The numpad enter is something that is not possible add this moment
