### ISSUE TITLE
Vicreo Hotkey: Open a file - path syntax issue (MacOS)

### ISSUE THREAD

**Issue by lfrisk** [JeffreyDavidsz/VICREO-Listener#83]
I am attempting to open OBS in my applications folder using VICREO hotkey: Open a file.  I followed the instructions on how to find the file path, but each attempt I make receives the same error:
"please change to new syntax"

Am I supposed to add something to the pathway? I do not see any documentation on new syntax, the only guidance I see is "without quotes"

Example pathways I have tried:

- /Applications/OBS.app
- ~/Library/Applications/OBS.app
- /Macintosh HD/Library/Applications/OBS.app

**Comment by JeffreyDavidsz** [comment]
You are using companion with the wrong version selected in the instance. Check the instance setting in companion change it to > 2.5 or something like that

**Comment by lfrisk** [comment]
Jeffrey, 

I was able to get the Open a file command to work by putting quotes around the pathway.
![Screen Shot 2021-06-29 at 3 43 30 PM](https://user-images.githubusercontent.com/74016050/123864813-cc85bf00-d8f0-11eb-82ff-5b429d325801.png)

Companion 2.1.3
VICREO Listener 2.0.9
-Selected ">2.0.5" in Companion Instance settings
